# Generated by Django 3.2.9 on 2021-11-14 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0002_issue_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue', to=settings.AUTH_USER_MODEL),
        ),
    ]
