# Generated by Django 3.2.9 on 2021-11-14 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0003_alter_issue_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
