# Generated by Django 3.2.9 on 2021-11-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20211114_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue',
            new_name='user',
        ),
    ]
