# Generated by Django 3.2.9 on 2021-12-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_doctor_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Value')),
                ('doctor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor')),
            ],
        ),
    ]
