# Generated by Django 3.2.9 on 2021-11-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='accounts.rating'),
        ),
    ]
