# Generated by Django 3.2.9 on 2021-11-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211124_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
