# Generated by Django 3.2.9 on 2021-12-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='Doc', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(default='Pat', max_length=200),
        ),
    ]
