# Generated by Django 3.2.9 on 2021-11-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20211123_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifiedassignment',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
