# Generated by Django 3.2.9 on 2021-12-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_delete_pastappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.CharField(max_length=100),
        ),
    ]
